# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.248
neo_version_range=[21.1.200,)

# Dependencies
jei_version=19.25.0.322

# Mod properties
mod_id=coupons
mod_name=Coupons
mod_license=MIT License
mod_version=1.0.0
mod_group_id=de.artemis.coupons
mod_authors=DoomedArtemis
mod_description=Mod that adds various coupons to the game which each grant different discounts to Minecraft's gameplay
