# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
minecraft_version=1.21.5
minecraft_version_range=[1.21.5]

# NeoForge
neo_version=21.5.74
neo_version_range=[21.5.74,21.6)

# Dependencies
jei_version=21.4.0.27
jei_version_range=[21.0.0.1,)
rei_version=19.0.809
rei_version_range=[19.0.805,)
curios_version=11.0.1+1.21.5
curios_version_range=[11.0.0,)

# Mod properties
mod_id=coupon_codes
mod_name=Coupon Codes
mod_license=MIT License
mod_version=1.0.0
mod_group_id=de.doomedartemis.couponcodes
mod_authors=DoomedArtemis
mod_description=Mod that adds various coupon codes to the game which each grant different discounts to Minecraft's gameplay
