# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4]

# NeoForge
neo_version=21.4.121
neo_version_range=[21.4.121,21.5)

# Dependencies
jei_version=20.0.0.4
jei_version_range=[20.0.0.4,)
rei_version=18.0.815
rei_version_range=[18.0.795,)
curios_version=10.0.1+1.21.4
curios_version_range=[10.0.0,)

# Mod properties
mod_id=coupon_codes
mod_name=Coupon Codes
mod_license=MIT License
mod_version=1.0.0
mod_group_id=de.doomedartemis.couponcodes
mod_authors=DoomedArtemis
mod_description=Mod that adds various coupon codes to the game which each grant different discounts to Minecraft's gameplay
